title = "Dusan Haustein"
base_url = "https://dhaustein.github.io"
description = "Personal blog and website, on which I ramble at lenght about things both mundane and neat."

compile_sass = true
minify_html = false
generate_feeds = true

feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true

author = "Dusan Haustein"
default_language = "en"

theme = "duckquill"

taxonomies = [{ name = "tags", feed = false }]

[markdown]
smart_punctuation = true
bottom_footnotes = true
github_alerts = true

[markdown.highlighting]
theme = "dracula-soft"

[search]
# index_format = "elasticlunr_json"
index_format = "fuse_json"

[extra]
accent_color = "#ff7800"
accent_color_dark = "#ffa348"

styles = [
    "portrait.css"
]

[extra.nav]
show_theme_switcher = true
links = [
	{ url = "@/blog/_index.md", name = "Blog" },
	{ url = "https://github.com/dhaustein/cv/releases/download/dusan-haustein-cv-eng-latest/dusan-haustein-cv-eng.pdf", name = "CV" },
	{ url = "https://www.linkedin.com/in/dusanhaustein/", name = "LinkedIn" }
]
show_feed = true

[extra.footer]
show_copyright = true
show_powered_by = true
show_source = true
