title = "Dusan Haustein's Blog"
base_url = "https://dhaustein.github.io"
description = "Personal blog and website, on which I ramble at lenght about things both mundane and neat."

compile_sass = true
minify_html = false
generate_feeds = true

# Only the first file will be used in the navbar feed button,
# other feeds will still be available in page's head.
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true

author = "Dusan Haustein"
default_language = "en"

# Theme
theme = "duckquill"

taxonomies = [{ name = "tags", feed = true }]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

smart_punctuation = true
bottom_footnotes = true
github_alerts = false

[search]
# index_format = "elasticlunr_json"
index_format = "fuse_json"

[extra]
accent_color = "#ff7800"
accent_color_dark = "#ffa348"

